import {createBundle} from "./node/bundle.js";
import {openBrowser} from "./node/open-browser.js";
import {readManifest} from "./node/manifest.js";
import {projectGeometry} from "./proj4/gpkg-projection.js";
import {startServer} from "./server.js";
import * as databaseAdapter from "./sqlite/sqlite-adapter.js";

export const main = async (args) => {
  const options = parseArguments(args);
  if (options.help) {
    console.log(createHelpText());
    return;
  }
  if (options.command === "bundle") {
    const output = await createBundle(options.pmtiles, options.output);
    console.log(output);
    return;
  }
  const {manifest, root} = await readManifest(options.output);
  const diagnosticLog = options.verbose ? (event) => console.error(`preview debug: ${JSON.stringify(event)}`) : undefined;
  const {server, url} = await startServer(root, {
    databaseAdapter,
    diagnosticLog,
    manifest,
    port: options.port,
    projectGeometry,
    verbose: options.verbose,
  });
  console.log(url);
  if (!options.noOpen) {
    await openBrowser(url).catch((error) => {
      console.error(`warning: browser launch failed: ${error.message}`);
    });
  }
  await waitForShutdown(server);
  if (server.previewError) throw server.previewError;
};

export const parseArguments = (args) => {
  if (args.includes("--help") || args.includes("-h")) return {help: true};
  if (args[0] === "preview") return parsePreviewArguments(args.slice(1));
  if (args[0] === "bundle") return parseBundleArguments(args.slice(1));
  return parsePreviewArguments(args);
};

export const createHelpText = () => [
  "dm-preview - preview MapLibre output generated by dm-converter",
  "",
  "Usage:",
  "  dm-preview preview OUTPUT [--no-open] [--port PORT] [--verbose]",
  "  dm-preview bundle PMTILES OUTPUT",
  "  dm-preview OUTPUT [--no-open] [--port PORT]",
  "  dm-preview --help",
  "",
  "Commands:",
  "  preview  Start a local preview server for a MapLibre output directory.",
  "           OUTPUT is resolved from the current working directory.",
  "           The legacy form without the preview command is also supported.",
  "  bundle   Copy PMTILES and required preview assets into OUTPUT for distribution.",
  "           OUTPUT must be empty or absent.",
  "",
  "Preview options:",
  "  --no-open       Print the preview URL without opening a browser.",
  "  --port PORT     Listen on PORT. Use an available random port when omitted.",
  "  --verbose       Print asset roots and failed static-file lookups to stderr.",
  "",
  "Preview URL parameters:",
  "  coords=lng,lat  Initial or last map center.",
  "  scale=NUMBER    Initial or last map scale.",
  "  layers=NAME     Selected feature-list layer.",
  "",
  "Examples:",
  "  dm-preview preview ./public",
  "  dm-preview preview ./public --no-open --port 3000",
  "  dm-preview bundle ./maplibre/dm.pmtiles ./public",
  "",
  "Exit codes:",
  "  0  Success.",
  "  1  Runtime error, such as server startup failure.",
  "  2  Input or manifest error.",
].join("\n");

const parsePreviewArguments = (args) => {
  const noOpen = args.includes("--no-open");
  const verbose = args.includes("--verbose");
  const {port, rest} = parsePortOption(args);
  const unknown = rest.filter((value) => value.startsWith("-") && value !== "--no-open" && value !== "--verbose");
  const positional = rest.filter((value) => !value.startsWith("-"));
  if (unknown.length) throw inputError(`unknown option: ${unknown[0]}`);
  if (positional.length !== 1) throw inputError("preview requires exactly one OUTPUT directory");
  return {command: "preview", help: false, noOpen, output: positional[0], ...(port ? {port} : {}), ...(verbose ? {verbose} : {})};
};

const parseBundleArguments = (args) => {
  const unknown = args.filter((value) => value.startsWith("-"));
  if (unknown.length) throw inputError(`unknown option: ${unknown[0]}`);
  if (args.length !== 2) throw inputError("bundle requires PMTILES and OUTPUT");
  return {command: "bundle", help: false, pmtiles: args[0], output: args[1]};
};

const waitForShutdown = (server) => new Promise((resolve) => {
  const close = () => server.close(resolve);
  process.once("SIGINT", close);
  process.once("SIGTERM", close);
});

const parsePortOption = (args) => {
  const rest = [];
  let port;
  for (let index = 0; index < args.length; index += 1) {
    const value = args[index];
    if (value === "--port") {
      port = parsePortValue(args[index + 1]);
      index += 1;
    } else if (value.startsWith("--port=")) {
      port = parsePortValue(value.slice("--port=".length));
    } else {
      rest.push(value);
    }
  }
  return {port, rest};
};

const parsePortValue = (value) => {
  if (!/^[0-9]+$/.test(value ?? "")) throw inputError("port must be an integer from 1 to 65535");
  const port = Number(value);
  if (port < 1 || port > 65535) throw inputError("port must be an integer from 1 to 65535");
  return port;
};

const inputError = (message) => Object.assign(new Error(message), {name: "InputError"});
